apiVersion: apps/v1 
kind: Deployment
metadata:
  name: fullstack-app-postgres 
  labels:
    app: fullstack-app-postgres
spec:
  replicas: 1  
  selector:
    matchLabels: 
      app: fullstack-app-postgres
  template:   
    metadata:
      labels: 
        app: fullstack-app-postgres
    spec: 
      containers:
      - name: fullstack-app-postgres 
        image: victorsteven/fullstack:1.3.0
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080 
        envFrom:
          - secretRef:
              name: postgres-secret
      

apiVersion: v1  
kind: Service 
metadata:
  name: fullstack-app-postgres
  labels:
    app: fullstack-app-postgres
spec:
  type: NodePort  
  selector:
    app: fullstack-app-postgres 
  ports: 
  - name: http
    port: 8080
    targetPort: 8080